show_author_username:
  type: bool
  default: false
  description:
    en: "Show author username instead profile avatar"
show_author_before_topic:
  type: bool
  default: false
  description:
    en: "Show author avatar before topic column on desktop"
