show_author_username:
  type: bool
  default: false
  description:
    en: "Display author username after topic column instead profile avatar"
show_author_before_topic:
  type: bool
  default: false
  description:
    en: "Display author avatar before topic column"
